window.esdocSearchIndex = [
  [
    "src/account/accountpage/accountpage.js~accountpage",
    "class/src/account/accountPage/AccountPage.js~AccountPage.html",
    "<span>AccountPage</span> <span class=\"search-result-import-path\">src/account/accountPage/AccountPage.js</span>",
    "class"
  ],
  [
    "src/app.js~app",
    "class/src/App.js~App.html",
    "<span>App</span> <span class=\"search-result-import-path\">src/App.js</span>",
    "class"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html",
    "<span>CarouselDIV</span> <span class=\"search-result-import-path\">src/welcomePage/carouselDIV.js</span>",
    "class"
  ],
  [
    "src/account/emailverification/index.js~emailverification",
    "class/src/account/EmailVerification/index.js~EmailVerification.html",
    "<span>EmailVerification</span> <span class=\"search-result-import-path\">src/account/EmailVerification/index.js</span>",
    "class"
  ],
  [
    "src/account/actions/types.js~get_errors",
    "variable/index.html#static-variable-GET_ERRORS",
    "<span>GET_ERRORS</span> <span class=\"search-result-import-path\">src/account/actions/types.js</span>",
    "variable"
  ],
  [
    "src/account/components/kfaccountinput.js~kfaccountinput",
    "function/index.html#static-function-KFAccountInput",
    "<span>KFAccountInput</span> <span class=\"search-result-import-path\">src/account/components/KFAccountInput.js</span>",
    "function"
  ],
  [
    "src/routers/mainrouter.js~mainroute",
    "function/index.html#static-function-MainRoute",
    "<span>MainRoute</span> <span class=\"search-result-import-path\">src/routers/mainRouter.js</span>",
    "function"
  ],
  [
    "src/account/actions/types.js~set_current_user",
    "variable/index.html#static-variable-SET_CURRENT_USER",
    "<span>SET_CURRENT_USER</span> <span class=\"search-result-import-path\">src/account/actions/types.js</span>",
    "variable"
  ],
  [
    "src/account/utils/verifyemail.js~verifyemail",
    "class/src/account/utils/verifyEmail.js~VerifyEmail.html",
    "<span>VerifyEmail</span> <span class=\"search-result-import-path\">src/account/utils/verifyEmail.js</span>",
    "class"
  ],
  [
    "src/account/reducers/authreducer.js~authreducer",
    "function/index.html#static-function-authReducer",
    "<span>authReducer</span> <span class=\"search-result-import-path\">src/account/reducers/authReducer.js</span>",
    "function"
  ],
  [
    "src/headerpage/headerpagecss.js~avatarstyle",
    "variable/index.html#static-variable-avatarStyle",
    "<span>avatarStyle</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/footerpage/footerpagecss.js~background",
    "variable/index.html#static-variable-background",
    "<span>background</span> <span class=\"search-result-import-path\">src/footerPage/footerPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~background",
    "variable/index.html#static-variable-background",
    "<span>background</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/bookspage/bookspagecss.js~bookimage",
    "variable/index.html#static-variable-bookImage",
    "<span>bookImage</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/bookspage/bookspagecss.js~bookinfo",
    "variable/index.html#static-variable-bookInfo",
    "<span>bookInfo</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/allcategoriespage/categoriespagecss.js~bookrow",
    "variable/index.html#static-variable-bookRow",
    "<span>bookRow</span> <span class=\"search-result-import-path\">src/allCategoriesPage/categoriesPageCss.js</span>",
    "variable"
  ],
  [
    "src/allcategoriespage/categoriespagecss.js~bookscontainer",
    "variable/index.html#static-variable-booksContainer",
    "<span>booksContainer</span> <span class=\"search-result-import-path\">src/allCategoriesPage/categoriesPageCss.js</span>",
    "variable"
  ],
  [
    "src/allcategoriespage/booksincategory.js~bookspage",
    "class/src/allCategoriesPage/booksInCategory.js~booksPage.html",
    "<span>booksPage</span> <span class=\"search-result-import-path\">src/allCategoriesPage/booksInCategory.js</span>",
    "class"
  ],
  [
    "src/bookspage/component.js~bookspagecomponent",
    "function/index.html#static-function-booksPageComponent",
    "<span>booksPageComponent</span> <span class=\"search-result-import-path\">src/booksPage/component.js</span>",
    "function"
  ],
  [
    "src/bookspage/bookspagereducer.js~bookspagereducer",
    "function/index.html#static-function-booksPageReducer",
    "<span>booksPageReducer</span> <span class=\"search-result-import-path\">src/booksPage/booksPageReducer.js</span>",
    "function"
  ],
  [
    "src/allcategoriespage/categoriespagecss.js~breadcrumbtrail",
    "variable/index.html#static-variable-breadcrumbTrail",
    "<span>breadcrumbTrail</span> <span class=\"search-result-import-path\">src/allCategoriesPage/categoriesPageCss.js</span>",
    "variable"
  ],
  [
    "src/welcomepage/welcomepagecss.js~carouseldive",
    "variable/index.html#static-variable-carouselDive",
    "<span>carouselDive</span> <span class=\"search-result-import-path\">src/welcomePage/welcomePageCss.js</span>",
    "variable"
  ],
  [
    "src/allcategoriespage/categoriespagecss.js~categoriescontainer",
    "variable/index.html#static-variable-categoriesContainer",
    "<span>categoriesContainer</span> <span class=\"search-result-import-path\">src/allCategoriesPage/categoriesPageCss.js</span>",
    "variable"
  ],
  [
    "src/allcategoriespage/categoriespagereducer.js~categoriespagereducer",
    "function/index.html#static-function-categoriesPageReducer",
    "<span>categoriesPageReducer</span> <span class=\"search-result-import-path\">src/allCategoriesPage/categoriesPageReducer.js</span>",
    "function"
  ],
  [
    "src/bookspage/bookspagecss.js~center",
    "variable/index.html#static-variable-center",
    "<span>center</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/config.js~config",
    "variable/index.html#static-variable-config",
    "<span>config</span> <span class=\"search-result-import-path\">src/config.js</span>",
    "variable"
  ],
  [
    "src/bookspage/bookspagecss.js~container",
    "variable/index.html#static-variable-container",
    "<span>container</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/footerpage/footerpagecss.js~containerdiv",
    "variable/index.html#static-variable-containerDiv",
    "<span>containerDiv</span> <span class=\"search-result-import-path\">src/footerPage/footerPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~containerdiv",
    "variable/index.html#static-variable-containerDiv",
    "<span>containerDiv</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/bookspage/bookspagecss.js~containerofpersonalreview",
    "variable/index.html#static-variable-containerOfPersonalReview",
    "<span>containerOfPersonalReview</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/welcomepage/welcomepagecss.js~eachbook",
    "variable/index.html#static-variable-eachBook",
    "<span>eachBook</span> <span class=\"search-result-import-path\">src/welcomePage/welcomePageCss.js</span>",
    "variable"
  ],
  [
    "src/account/reducers/errorreducer.js~errorreducer",
    "function/index.html#static-function-errorReducer",
    "<span>errorReducer</span> <span class=\"search-result-import-path\">src/account/reducers/errorReducer.js</span>",
    "function"
  ],
  [
    "src/footerpage/index.js~footerpageindex",
    "function/index.html#static-function-footerPageIndex",
    "<span>footerPageIndex</span> <span class=\"search-result-import-path\">src/footerPage/index.js</span>",
    "function"
  ],
  [
    "src/footerpage/footerpagecss.js~footerword",
    "variable/index.html#static-variable-footerWord",
    "<span>footerWord</span> <span class=\"search-result-import-path\">src/footerPage/footerPageCss.js</span>",
    "variable"
  ],
  [
    "src/allcategoriespage/categoriespagecss.js~hrtag",
    "variable/index.html#static-variable-hrTag",
    "<span>hrTag</span> <span class=\"search-result-import-path\">src/allCategoriesPage/categoriesPageCss.js</span>",
    "variable"
  ],
  [
    "src/footerpage/footerpagecss.js~iconlogo",
    "variable/index.html#static-variable-iconLogo",
    "<span>iconLogo</span> <span class=\"search-result-import-path\">src/footerPage/footerPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~iconlogo",
    "variable/index.html#static-variable-iconLogo",
    "<span>iconLogo</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/allcategoriespage/categoriespagecss.js~insideul",
    "variable/index.html#static-variable-insideUl",
    "<span>insideUl</span> <span class=\"search-result-import-path\">src/allCategoriesPage/categoriesPageCss.js</span>",
    "variable"
  ],
  [
    "src/account/validation/isempty.js~isempty",
    "function/index.html#static-function-isEmpty",
    "<span>isEmpty</span> <span class=\"search-result-import-path\">src/account/validation/isEmpty.js</span>",
    "function"
  ],
  [
    "src/account/actions/authactions.js~loginuser",
    "function/index.html#static-function-loginUser",
    "<span>loginUser</span> <span class=\"search-result-import-path\">src/account/actions/authActions.js</span>",
    "function"
  ],
  [
    "src/headerpage/headerpagecss.js~logopart",
    "variable/index.html#static-variable-logoPart",
    "<span>logoPart</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/account/actions/authactions.js~logoutuser",
    "function/index.html#static-function-logoutUser",
    "<span>logoutUser</span> <span class=\"search-result-import-path\">src/account/actions/authActions.js</span>",
    "function"
  ],
  [
    "src/bookspage/bookspagecss.js~mainview",
    "variable/index.html#static-variable-mainView",
    "<span>mainView</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~navspan",
    "variable/index.html#static-variable-navSpan",
    "<span>navSpan</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~navigation",
    "variable/index.html#static-variable-navigation",
    "<span>navigation</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~navigationsub",
    "variable/index.html#static-variable-navigationSub",
    "<span>navigationSub</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/welcomepage/popularbooks.js~popularbookscomponent",
    "function/index.html#static-function-popularBooksComponent",
    "<span>popularBooksComponent</span> <span class=\"search-result-import-path\">src/welcomePage/popularBooks.js</span>",
    "function"
  ],
  [
    "src/registerserviceworker.js~register",
    "function/index.html#static-function-register",
    "<span>register</span> <span class=\"search-result-import-path\">src/registerServiceWorker.js</span>",
    "function"
  ],
  [
    "src/account/actions/authactions.js~registeruser",
    "function/index.html#static-function-registerUser",
    "<span>registerUser</span> <span class=\"search-result-import-path\">src/account/actions/authActions.js</span>",
    "function"
  ],
  [
    "src/bookspage/bookspagecss.js~reviewcontent",
    "variable/index.html#static-variable-reviewContent",
    "<span>reviewContent</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~righticon",
    "variable/index.html#static-variable-rightIcon",
    "<span>rightIcon</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/bookspage/bookspagecss.js~rightpart",
    "variable/index.html#static-variable-rightPart",
    "<span>rightPart</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/headerpage/headerpagecss.js~searchicon",
    "variable/index.html#static-variable-searchIcon",
    "<span>searchIcon</span> <span class=\"search-result-import-path\">src/headerPage/headerPageCss.js</span>",
    "variable"
  ],
  [
    "src/bookspage/actions.js~selectbooknumberaction",
    "function/index.html#static-function-selectBookNumberAction",
    "<span>selectBookNumberAction</span> <span class=\"search-result-import-path\">src/booksPage/actions.js</span>",
    "function"
  ],
  [
    "src/account/utils/setauthtokeninheader.js~setauthtokeninheader",
    "function/index.html#static-function-setAuthTokenInHeader",
    "<span>setAuthTokenInHeader</span> <span class=\"search-result-import-path\">src/account/utils/setAuthTokenInHeader.js</span>",
    "function"
  ],
  [
    "src/account/actions/authactions.js~setcurrentuser",
    "function/index.html#static-function-setCurrentUser",
    "<span>setCurrentUser</span> <span class=\"search-result-import-path\">src/account/actions/authActions.js</span>",
    "function"
  ],
  [
    "src/allcategoriespage/actions.js~showbooksincategoryaction",
    "function/index.html#static-function-showBooksinCategoryAction",
    "<span>showBooksinCategoryAction</span> <span class=\"search-result-import-path\">src/allCategoriesPage/actions.js</span>",
    "function"
  ],
  [
    "src/store.js~store",
    "variable/index.html#static-variable-store",
    "<span>store</span> <span class=\"search-result-import-path\">src/store.js</span>",
    "variable"
  ],
  [
    "src/account/accountstyles.js~styles",
    "variable/index.html#static-variable-styles",
    "<span>styles</span> <span class=\"search-result-import-path\">src/account/AccountStyles.js</span>",
    "variable"
  ],
  [
    "src/registerserviceworker.js~unregister",
    "function/index.html#static-function-unregister",
    "<span>unregister</span> <span class=\"search-result-import-path\">src/registerServiceWorker.js</span>",
    "function"
  ],
  [
    "src/bookspage/bookspagecss.js~userheadimage",
    "variable/index.html#static-variable-userHeadImage",
    "<span>userHeadImage</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/bookspage/bookspagecss.js~viewpersonalinfromation",
    "variable/index.html#static-variable-viewPersonalInfromation",
    "<span>viewPersonalInfromation</span> <span class=\"search-result-import-path\">src/booksPage/booksPageCss.js</span>",
    "variable"
  ],
  [
    "src/welcomepage/index.js~welcomepageindex",
    "class/src/welcomePage/index.js~welcomePageIndex.html",
    "<span>welcomePageIndex</span> <span class=\"search-result-import-path\">src/welcomePage/index.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/app.js",
    "file/src/App.js.html",
    "src/App.js",
    "file"
  ],
  [
    "src/app.js~app#render",
    "class/src/App.js~App.html#instance-method-render",
    "src/App.js~App#render",
    "method"
  ],
  [
    "src/app.test.js",
    "file/src/App.test.js.html",
    "src/App.test.js",
    "file"
  ],
  [
    "src/account/accountstyles.js",
    "file/src/account/AccountStyles.js.html",
    "src/account/AccountStyles.js",
    "file"
  ],
  [
    "src/account/emailverification/index.js",
    "file/src/account/EmailVerification/index.js.html",
    "src/account/EmailVerification/index.js",
    "file"
  ],
  [
    "src/account/emailverification/index.js~emailverification#countdown",
    "class/src/account/EmailVerification/index.js~EmailVerification.html#instance-member-countDown",
    "src/account/EmailVerification/index.js~EmailVerification#countDown",
    "member"
  ],
  [
    "src/account/emailverification/index.js~emailverification#render",
    "class/src/account/EmailVerification/index.js~EmailVerification.html#instance-method-render",
    "src/account/EmailVerification/index.js~EmailVerification#render",
    "method"
  ],
  [
    "src/account/emailverification/index.js~emailverification#resendactivationemail",
    "class/src/account/EmailVerification/index.js~EmailVerification.html#instance-member-resendActivationEmail",
    "src/account/EmailVerification/index.js~EmailVerification#resendActivationEmail",
    "member"
  ],
  [
    "src/account/emailverification/index.js~emailverification#state",
    "class/src/account/EmailVerification/index.js~EmailVerification.html#instance-member-state",
    "src/account/EmailVerification/index.js~EmailVerification#state",
    "member"
  ],
  [
    "src/account/accountpage/accountpage.js",
    "file/src/account/accountPage/AccountPage.js.html",
    "src/account/accountPage/AccountPage.js",
    "file"
  ],
  [
    "src/account/accountpage/accountpage.js~accountpage#componentdidmount",
    "class/src/account/accountPage/AccountPage.js~AccountPage.html#instance-method-componentDidMount",
    "src/account/accountPage/AccountPage.js~AccountPage#componentDidMount",
    "method"
  ],
  [
    "src/account/accountpage/accountpage.js~accountpage#render",
    "class/src/account/accountPage/AccountPage.js~AccountPage.html#instance-method-render",
    "src/account/accountPage/AccountPage.js~AccountPage#render",
    "method"
  ],
  [
    "src/account/accountpage/accountpage.js~accountpage#state",
    "class/src/account/accountPage/AccountPage.js~AccountPage.html#instance-member-state",
    "src/account/accountPage/AccountPage.js~AccountPage#state",
    "member"
  ],
  [
    "src/account/accountpage/accountpage.test.js",
    "file/src/account/accountPage/AccountPage.test.js.html",
    "src/account/accountPage/AccountPage.test.js",
    "file"
  ],
  [
    "src/account/actions/authactions.js",
    "file/src/account/actions/authActions.js.html",
    "src/account/actions/authActions.js",
    "file"
  ],
  [
    "src/account/actions/types.js",
    "file/src/account/actions/types.js.html",
    "src/account/actions/types.js",
    "file"
  ],
  [
    "src/account/components/kfaccountinput.js",
    "file/src/account/components/KFAccountInput.js.html",
    "src/account/components/KFAccountInput.js",
    "file"
  ],
  [
    "src/account/loginform/index.js",
    "file/src/account/loginForm/index.js.html",
    "src/account/loginForm/index.js",
    "file"
  ],
  [
    "src/account/reducers/authreducer.js",
    "file/src/account/reducers/authReducer.js.html",
    "src/account/reducers/authReducer.js",
    "file"
  ],
  [
    "src/account/reducers/errorreducer.js",
    "file/src/account/reducers/errorReducer.js.html",
    "src/account/reducers/errorReducer.js",
    "file"
  ],
  [
    "src/account/registerpage/index.js",
    "file/src/account/registerPage/index.js.html",
    "src/account/registerPage/index.js",
    "file"
  ],
  [
    "src/account/registerpage/register.test.js",
    "file/src/account/registerPage/register.test.js.html",
    "src/account/registerPage/register.test.js",
    "file"
  ],
  [
    "src/account/utils/setauthtokeninheader.js",
    "file/src/account/utils/setAuthTokenInHeader.js.html",
    "src/account/utils/setAuthTokenInHeader.js",
    "file"
  ],
  [
    "src/account/utils/verifyemail.js",
    "file/src/account/utils/verifyEmail.js.html",
    "src/account/utils/verifyEmail.js",
    "file"
  ],
  [
    "src/account/utils/verifyemail.js~verifyemail#componentdidmount",
    "class/src/account/utils/verifyEmail.js~VerifyEmail.html#instance-method-componentDidMount",
    "src/account/utils/verifyEmail.js~VerifyEmail#componentDidMount",
    "method"
  ],
  [
    "src/account/utils/verifyemail.js~verifyemail#render",
    "class/src/account/utils/verifyEmail.js~VerifyEmail.html#instance-method-render",
    "src/account/utils/verifyEmail.js~VerifyEmail#render",
    "method"
  ],
  [
    "src/account/utils/verifyemail.js~verifyemail#state",
    "class/src/account/utils/verifyEmail.js~VerifyEmail.html#instance-member-state",
    "src/account/utils/verifyEmail.js~VerifyEmail#state",
    "member"
  ],
  [
    "src/account/utils/verifyemail.js~verifyemail#verify",
    "class/src/account/utils/verifyEmail.js~VerifyEmail.html#instance-member-verify",
    "src/account/utils/verifyEmail.js~VerifyEmail#verify",
    "member"
  ],
  [
    "src/account/validation/isempty.js",
    "file/src/account/validation/isEmpty.js.html",
    "src/account/validation/isEmpty.js",
    "file"
  ],
  [
    "src/allcategoriespage/abook.js",
    "file/src/allCategoriesPage/aBook.js.html",
    "src/allCategoriesPage/aBook.js",
    "file"
  ],
  [
    "src/allcategoriespage/actions.js",
    "file/src/allCategoriesPage/actions.js.html",
    "src/allCategoriesPage/actions.js",
    "file"
  ],
  [
    "src/allcategoriespage/booksincategory.js",
    "file/src/allCategoriesPage/booksInCategory.js.html",
    "src/allCategoriesPage/booksInCategory.js",
    "file"
  ],
  [
    "src/allcategoriespage/booksincategory.js~bookspage#componentdidmount",
    "class/src/allCategoriesPage/booksInCategory.js~booksPage.html#instance-method-componentDidMount",
    "src/allCategoriesPage/booksInCategory.js~booksPage#componentDidMount",
    "method"
  ],
  [
    "src/allcategoriespage/booksincategory.js~bookspage#componentdidupdate",
    "class/src/allCategoriesPage/booksInCategory.js~booksPage.html#instance-method-componentDidUpdate",
    "src/allCategoriesPage/booksInCategory.js~booksPage#componentDidUpdate",
    "method"
  ],
  [
    "src/allcategoriespage/booksincategory.js~bookspage#constructor",
    "class/src/allCategoriesPage/booksInCategory.js~booksPage.html#instance-constructor-constructor",
    "src/allCategoriesPage/booksInCategory.js~booksPage#constructor",
    "method"
  ],
  [
    "src/allcategoriespage/booksincategory.js~bookspage#render",
    "class/src/allCategoriesPage/booksInCategory.js~booksPage.html#instance-method-render",
    "src/allCategoriesPage/booksInCategory.js~booksPage#render",
    "method"
  ],
  [
    "src/allcategoriespage/booksincategory.js~bookspage#state",
    "class/src/allCategoriesPage/booksInCategory.js~booksPage.html#instance-member-state",
    "src/allCategoriesPage/booksInCategory.js~booksPage#state",
    "member"
  ],
  [
    "src/allcategoriespage/categoriesbar.js",
    "file/src/allCategoriesPage/categoriesBar.js.html",
    "src/allCategoriesPage/categoriesBar.js",
    "file"
  ],
  [
    "src/allcategoriespage/categoriespagecss.js",
    "file/src/allCategoriesPage/categoriesPageCss.js.html",
    "src/allCategoriesPage/categoriesPageCss.js",
    "file"
  ],
  [
    "src/allcategoriespage/categoriespagereducer.js",
    "file/src/allCategoriesPage/categoriesPageReducer.js.html",
    "src/allCategoriesPage/categoriesPageReducer.js",
    "file"
  ],
  [
    "src/allcategoriespage/childcategories.js",
    "file/src/allCategoriesPage/childCategories.js.html",
    "src/allCategoriesPage/childCategories.js",
    "file"
  ],
  [
    "src/allcategoriespage/index.js",
    "file/src/allCategoriesPage/index.js.html",
    "src/allCategoriesPage/index.js",
    "file"
  ],
  [
    "src/bookspage/actions.js",
    "file/src/booksPage/actions.js.html",
    "src/booksPage/actions.js",
    "file"
  ],
  [
    "src/bookspage/bookspagecss.js",
    "file/src/booksPage/booksPageCss.js.html",
    "src/booksPage/booksPageCss.js",
    "file"
  ],
  [
    "src/bookspage/bookspagereducer.js",
    "file/src/booksPage/booksPageReducer.js.html",
    "src/booksPage/booksPageReducer.js",
    "file"
  ],
  [
    "src/bookspage/component.js",
    "file/src/booksPage/component.js.html",
    "src/booksPage/component.js",
    "file"
  ],
  [
    "src/bookspage/index.js",
    "file/src/booksPage/index.js.html",
    "src/booksPage/index.js",
    "file"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/footerpage/footerpagecss.js",
    "file/src/footerPage/footerPageCss.js.html",
    "src/footerPage/footerPageCss.js",
    "file"
  ],
  [
    "src/footerpage/index.js",
    "file/src/footerPage/index.js.html",
    "src/footerPage/index.js",
    "file"
  ],
  [
    "src/headerpage/badgeicon.js",
    "file/src/headerPage/badgeIcon.js.html",
    "src/headerPage/badgeIcon.js",
    "file"
  ],
  [
    "src/headerpage/headerpagecss.js",
    "file/src/headerPage/headerPageCss.js.html",
    "src/headerPage/headerPageCss.js",
    "file"
  ],
  [
    "src/headerpage/index.js",
    "file/src/headerPage/index.js.html",
    "src/headerPage/index.js",
    "file"
  ],
  [
    "src/headerpage/navigationbar.js",
    "file/src/headerPage/navigationBar.js.html",
    "src/headerPage/navigationBar.js",
    "file"
  ],
  [
    "src/headerpage/searchicon.js",
    "file/src/headerPage/searchIcon.js.html",
    "src/headerPage/searchIcon.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/reducers.js",
    "file/src/reducers.js.html",
    "src/reducers.js",
    "file"
  ],
  [
    "src/registerserviceworker.js",
    "file/src/registerServiceWorker.js.html",
    "src/registerServiceWorker.js",
    "file"
  ],
  [
    "src/routers/mainrouter.js",
    "file/src/routers/mainRouter.js.html",
    "src/routers/mainRouter.js",
    "file"
  ],
  [
    "src/store.js",
    "file/src/store.js.html",
    "src/store.js",
    "file"
  ],
  [
    "src/welcomepage/carouseldiv.js",
    "file/src/welcomePage/carouselDIV.js.html",
    "src/welcomePage/carouselDIV.js",
    "file"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#animating",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-member-animating",
    "src/welcomePage/carouselDIV.js~CarouselDIV#animating",
    "member"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#constructor",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-constructor-constructor",
    "src/welcomePage/carouselDIV.js~CarouselDIV#constructor",
    "method"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#gotoindex",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-method-goToIndex",
    "src/welcomePage/carouselDIV.js~CarouselDIV#goToIndex",
    "method"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#next",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-method-next",
    "src/welcomePage/carouselDIV.js~CarouselDIV#next",
    "method"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#onexited",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-method-onExited",
    "src/welcomePage/carouselDIV.js~CarouselDIV#onExited",
    "method"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#onexiting",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-method-onExiting",
    "src/welcomePage/carouselDIV.js~CarouselDIV#onExiting",
    "method"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#previous",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-method-previous",
    "src/welcomePage/carouselDIV.js~CarouselDIV#previous",
    "method"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#render",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-method-render",
    "src/welcomePage/carouselDIV.js~CarouselDIV#render",
    "method"
  ],
  [
    "src/welcomepage/carouseldiv.js~carouseldiv#state",
    "class/src/welcomePage/carouselDIV.js~CarouselDIV.html#instance-member-state",
    "src/welcomePage/carouselDIV.js~CarouselDIV#state",
    "member"
  ],
  [
    "src/welcomepage/index.js",
    "file/src/welcomePage/index.js.html",
    "src/welcomePage/index.js",
    "file"
  ],
  [
    "src/welcomepage/index.js~welcomepageindex#componentdidmount",
    "class/src/welcomePage/index.js~welcomePageIndex.html#instance-method-componentDidMount",
    "src/welcomePage/index.js~welcomePageIndex#componentDidMount",
    "method"
  ],
  [
    "src/welcomepage/index.js~welcomepageindex#constructor",
    "class/src/welcomePage/index.js~welcomePageIndex.html#instance-constructor-constructor",
    "src/welcomePage/index.js~welcomePageIndex#constructor",
    "method"
  ],
  [
    "src/welcomepage/index.js~welcomepageindex#render",
    "class/src/welcomePage/index.js~welcomePageIndex.html#instance-method-render",
    "src/welcomePage/index.js~welcomePageIndex#render",
    "method"
  ],
  [
    "src/welcomepage/index.js~welcomepageindex#state",
    "class/src/welcomePage/index.js~welcomePageIndex.html#instance-member-state",
    "src/welcomePage/index.js~welcomePageIndex#state",
    "member"
  ],
  [
    "src/welcomepage/popularbooks.js",
    "file/src/welcomePage/popularBooks.js.html",
    "src/welcomePage/popularBooks.js",
    "file"
  ],
  [
    "src/welcomepage/welcomepagecss.js",
    "file/src/welcomePage/welcomePageCss.js.html",
    "src/welcomePage/welcomePageCss.js",
    "file"
  ]
]